// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: appointments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addParticipantToAppointment = `-- name: AddParticipantToAppointment :exec
insert into appointment_participants (appointment_id, client_id)
values ($1, $2)
`

type AddParticipantToAppointmentParams struct {
	AppointmentID pgtype.UUID
	ClientID      pgtype.UUID
}

func (q *Queries) AddParticipantToAppointment(ctx context.Context, arg AddParticipantToAppointmentParams) error {
	_, err := q.db.Exec(ctx, addParticipantToAppointment, arg.AppointmentID, arg.ClientID)
	return err
}

const bookSlot = `-- name: BookSlot :one
insert into appointments (slot_id)
select s.id
from slots s
where s.id = $1
  and s.is_free_slot = true
  and not exists (
      select 1
      from appointments a
      where a.slot_id = s.id
  )
returning id, slot_id, created_at
`

type BookSlotRow struct {
	ID        pgtype.UUID
	SlotID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
}

func (q *Queries) BookSlot(ctx context.Context, slotID pgtype.UUID) (BookSlotRow, error) {
	row := q.db.QueryRow(ctx, bookSlot, slotID)
	var i BookSlotRow
	err := row.Scan(&i.ID, &i.SlotID, &i.CreatedAt)
	return i, err
}

const getAppointmentWithDetails = `-- name: GetAppointmentWithDetails :one
select
    a.id as appointment_id,
    p.full_name as provider_name,
    p.timezone as provider_timezone,
    timezone(p.timezone, s.start_time)::date as date_of_day,
    s.start_time,
    s.end_time,
    timezone(p.timezone, s.start_time) as slot_start_at,
    timezone(p.timezone, s.end_time) as slot_end_at,
    s.available_multiple_participants,
    json_agg(
        json_build_object(
            'clientId', c.id,
            'fullName', c.full_name,
            'email', c.email
        )
        order by ap.created_at
    ) as participants
from appointments a
join slots s on s.id = a.slot_id
join providers p on p.id = s.provider_id
join appointment_participants ap on ap.appointment_id = a.id
join clients c on c.id = ap.client_id
where a.id = $1
group by a.id, p.full_name, p.timezone, s.start_time, s.end_time, s.available_multiple_participants
`

type GetAppointmentWithDetailsRow struct {
	AppointmentID                 pgtype.UUID
	ProviderName                  string
	ProviderTimezone              string
	DateOfDay                     pgtype.Date
	StartTime                     pgtype.Timestamptz
	EndTime                       pgtype.Timestamptz
	SlotStartAt                   interface{}
	SlotEndAt                     interface{}
	AvailableMultipleParticipants bool
	Participants                  []byte
}

func (q *Queries) GetAppointmentWithDetails(ctx context.Context, appointmentID pgtype.UUID) (GetAppointmentWithDetailsRow, error) {
	row := q.db.QueryRow(ctx, getAppointmentWithDetails, appointmentID)
	var i GetAppointmentWithDetailsRow
	err := row.Scan(
		&i.AppointmentID,
		&i.ProviderName,
		&i.ProviderTimezone,
		&i.DateOfDay,
		&i.StartTime,
		&i.EndTime,
		&i.SlotStartAt,
		&i.SlotEndAt,
		&i.AvailableMultipleParticipants,
		&i.Participants,
	)
	return i, err
}

const getProviderByUsername = `-- name: GetProviderByUsername :one
select
    p.id,
    p.full_name,
    p.email,
    p.username,
    p.timezone,
    p.bio
from providers p
where p.username = $1
`

type GetProviderByUsernameRow struct {
	ID       pgtype.UUID
	FullName string
	Email    string
	Username string
	Timezone string
	Bio      pgtype.Text
}

func (q *Queries) GetProviderByUsername(ctx context.Context, username string) (GetProviderByUsernameRow, error) {
	row := q.db.QueryRow(ctx, getProviderByUsername, username)
	var i GetProviderByUsernameRow
	err := row.Scan(
		&i.ID,
		&i.FullName,
		&i.Email,
		&i.Username,
		&i.Timezone,
		&i.Bio,
	)
	return i, err
}

const getSlotsByProviderUsernameAndDate = `-- name: GetSlotsByProviderUsernameAndDate :many
select
    s.id,
    timezone(p.timezone, s.start_time)::date as date_of_day,
    s.start_time,
    s.end_time,
    timezone(p.timezone, s.start_time) as slot_start_at,
    timezone(p.timezone, s.end_time) as slot_end_at,
    s.available_multiple_participants
from slots s
join providers p on p.id = s.provider_id
where p.username = $1
  and timezone(p.timezone, s.start_time)::date = $2
  and s.is_free_slot = true
  and (
      $3::timestamptz is null
      or s.start_time > $3::timestamptz
      or (
          s.start_time = $3::timestamptz
          and s.id > $4::uuid
      )
  )
order by s.start_time, s.id
limit $5
`

type GetSlotsByProviderUsernameAndDateParams struct {
	Username        string
	DateOfDay       string
	CursorStartTime pgtype.Timestamptz
	CursorID        pgtype.UUID
	Limit           int32
}

type GetSlotsByProviderUsernameAndDateRow struct {
	ID                            pgtype.UUID
	DateOfDay                     pgtype.Date
	StartTime                     pgtype.Timestamptz
	EndTime                       pgtype.Timestamptz
	SlotStartAt                   interface{}
	SlotEndAt                     interface{}
	AvailableMultipleParticipants bool
}

func (q *Queries) GetSlotsByProviderUsernameAndDate(ctx context.Context, arg GetSlotsByProviderUsernameAndDateParams) ([]GetSlotsByProviderUsernameAndDateRow, error) {
	rows, err := q.db.Query(ctx, getSlotsByProviderUsernameAndDate,
		arg.Username,
		arg.DateOfDay,
		arg.CursorStartTime,
		arg.CursorID,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSlotsByProviderUsernameAndDateRow
	for rows.Next() {
		var i GetSlotsByProviderUsernameAndDateRow
		if err := rows.Scan(
			&i.ID,
			&i.DateOfDay,
			&i.StartTime,
			&i.EndTime,
			&i.SlotStartAt,
			&i.SlotEndAt,
			&i.AvailableMultipleParticipants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertClientByEmail = `-- name: UpsertClientByEmail :one
insert into clients (full_name, email)
values ($1, $2)
on conflict (email)
do update
set full_name = excluded.full_name,
    updated_at = now()
returning id, full_name, email
`

type UpsertClientByEmailParams struct {
	FullName string
	Email    string
}

type UpsertClientByEmailRow struct {
	ID       pgtype.UUID
	FullName string
	Email    string
}

func (q *Queries) UpsertClientByEmail(ctx context.Context, arg UpsertClientByEmailParams) (UpsertClientByEmailRow, error) {
	row := q.db.QueryRow(ctx, upsertClientByEmail, arg.FullName, arg.Email)
	var i UpsertClientByEmailRow
	err := row.Scan(&i.ID, &i.FullName, &i.Email)
	return i, err
}
