// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Appointment struct {
	ID        pgtype.UUID
	SlotID    pgtype.UUID
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type AppointmentParticipant struct {
	ID            pgtype.UUID
	AppointmentID pgtype.UUID
	ClientID      pgtype.UUID
	CreatedAt     pgtype.Timestamptz
	UpdatedAt     pgtype.Timestamptz
}

type Client struct {
	ID        pgtype.UUID
	FullName  string
	Email     string
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Provider struct {
	ID        pgtype.UUID
	FullName  string
	Email     string
	Username  string
	Timezone  string
	Bio       pgtype.Text
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type Slot struct {
	ID                            pgtype.UUID
	ProviderID                    pgtype.UUID
	StartTime                     pgtype.Timestamptz
	EndTime                       pgtype.Timestamptz
	AvailableMultipleParticipants bool
	IsFreeSlot                    bool
	CreatedAt                     pgtype.Timestamptz
	UpdatedAt                     pgtype.Timestamptz
}
