/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/appointments": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    get?: never
    put?: never
    /**
     * Create appointment
     * @description Create an appointment for a free slot
     */
    post: {
      parameters: {
        query?: never
        header?: never
        path?: never
        cookie?: never
      }
      requestBody: {
        content: {
          "application/json": components["schemas"]["CreateAppointmentRequest"]
        }
      }
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["CreateAppointmentOutputBody"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
        /** @description Conflict */
        409: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
      }
    }
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/providers/{username}": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get a provider by username
     * @description Get a provider by username
     */
    get: {
      parameters: {
        query?: never
        header?: never
        path: {
          username: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["GetProviderOutputBody"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
  "/providers/{username}/availability": {
    parameters: {
      query?: never
      header?: never
      path?: never
      cookie?: never
    }
    /**
     * Get provider availability
     * @description Get provider availability for a local date
     */
    get: {
      parameters: {
        query?: {
          date?: string
          limit?: number
          cursorStartTime?: string
          cursorId?: string
        }
        header?: never
        path: {
          username: string
        }
        cookie?: never
      }
      requestBody?: never
      responses: {
        /** @description OK */
        200: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/json": components["schemas"]["AvailabilityResponse"]
          }
        }
        /** @description Bad Request */
        400: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
        /** @description Not Found */
        404: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
        /** @description Unprocessable Entity */
        422: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
        /** @description Internal Server Error */
        500: {
          headers: {
            [name: string]: unknown
          }
          content: {
            "application/problem+json": components["schemas"]["ErrorModel"]
          }
        }
      }
    }
    put?: never
    post?: never
    delete?: never
    options?: never
    head?: never
    patch?: never
    trace?: never
  }
}
export type webhooks = Record<string, never>
export interface components {
  schemas: {
    Appointment: {
      acceptMultipleParticipants: boolean
      /** Format: date */
      dateOfDay: string
      /** Format: date-time */
      endTimeLocal: string
      /** Format: date-time */
      endTimeUtc: string
      /** Format: uuid */
      id: string
      participants: components["schemas"]["AppointmentParticipant"][] | null
      providerName: string
      providerTimezone: string
      /** Format: date-time */
      startTimeLocal: string
      /** Format: date-time */
      startTimeUtc: string
    }
    AppointmentParticipant: {
      /** Format: uuid */
      clientId: string
      /** Format: email */
      email: string
      fullName: string
    }
    AppointmentSlot: {
      acceptMultipleParticipants: boolean
      /** Format: date */
      dateOfDay: string
      /** Format: date-time */
      endTimeLocal: string
      /** Format: date-time */
      endTimeUtc: string
      /** Format: uuid */
      id: string
      isAvailable: boolean
      /** Format: date-time */
      startTimeLocal: string
      /** Format: date-time */
      startTimeUtc: string
      timezone: string
    }
    AvailabilityResponse: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/AvailabilityResponse.json
       */
      readonly $schema?: string
      /** Format: date */
      dateOfDay: string
      nextCursor?: components["schemas"]["SlotCursor"]
      slots: components["schemas"]["AppointmentSlot"][] | null
      timezone: string
      username: string
    }
    CreateAppointmentClient: {
      /** Format: email */
      email: string
      fullName: string
    }
    CreateAppointmentOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CreateAppointmentOutputBody.json
       */
      readonly $schema?: string
      appointment: components["schemas"]["Appointment"]
    }
    CreateAppointmentRequest: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/CreateAppointmentRequest.json
       */
      readonly $schema?: string
      client?: components["schemas"]["CreateAppointmentClient"]
      clients?: components["schemas"]["CreateAppointmentClient"][]
      /** Format: uuid */
      slotId: string
      turnstileToken?: string
    }
    ErrorDetail: {
      /** @description Where the error occurred, e.g. 'body.items[3].tags' or 'path.thing-id' */
      location?: string
      /** @description Error message text */
      message?: string
      /** @description The value at the given location */
      value?: unknown
    }
    ErrorModel: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/ErrorModel.json
       */
      readonly $schema?: string
      /**
       * @description A human-readable explanation specific to this occurrence of the problem.
       * @example Property foo is required but is missing.
       */
      detail?: string
      /** @description Optional list of individual error details */
      errors?: components["schemas"]["ErrorDetail"][] | null
      /**
       * Format: uri
       * @description A URI reference that identifies the specific occurrence of the problem.
       * @example https://example.com/error-log/abc123
       */
      instance?: string
      /**
       * Format: int64
       * @description HTTP status code
       * @example 400
       */
      status?: number
      /**
       * @description A short, human-readable summary of the problem type. This value should not change between occurrences of the error.
       * @example Bad Request
       */
      title?: string
      /**
       * Format: uri
       * @description A URI reference to human-readable documentation for the error.
       * @default about:blank
       * @example https://example.com/errors/example
       */
      type: string
    }
    GetProviderOutputBody: {
      /**
       * Format: uri
       * @description A URL to the JSON Schema for this object.
       * @example https://example.com/schemas/GetProviderOutputBody.json
       */
      readonly $schema?: string
      provider: components["schemas"]["Provider"]
    }
    Provider: {
      /** @description Provider bio in markdown format */
      bio?: string | null
      fullName: string
      /** Format: uuid */
      id: string
      timezone: string
      username: string
    }
    SlotCursor: {
      /** Format: uuid */
      id: string
      /** Format: date-time */
      startTime: string
    }
  }
  responses: never
  parameters: never
  requestBodies: never
  headers: never
  pathItems: never
}
export type $defs = Record<string, never>
export type operations = Record<string, never>
